language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: qd0/M0hXDOk116DqXFUy1FpC2d+s6ATs9ryF5P4KbRxZxP4qeyEZLPPikffdRCOgYLXm8wjW4ESUbNyRHVKlYvj7Qi0Nn3oGmwn7T2ac9y0RIIVC66aN+UEPQlccyWS9fzyyupmQnHnZ4nWGex/Ri9MoieNc/tE8RUonDX+xTKSRcwNYqVifiCRX6ViDl6q50JPKsETjUu4eywefyECJNge8Ry66yaE29Nk1LEI3904hOZbI9jW6cSnXJBcCoQtFRH5BAlOYn3ei0vMnaa1VdVMe/w2VidxyqAWxy2qv8NkOeolroBWzIk/bR+HAXLDFqfHkvASUckq5LS1AOdhEaoJVYnMs65LmPBr+FysSdhVdwi6kocG2SbegJJTFnkQPVK2ctdKsz5iYUUOOQldbcdEJ08j2lu1AG/TAdcRSrB/P1G3PRgQc0QXMlmWY7O3xa2J6Qn9QohbMslbedBdF8zHiBPzfVVqImu2TR3wqHL+Am7Me4DNIFQAXruGj6QshZaT5ilgfthw0T9sWgZqIC/15flIgUEa0NMFmuLEJqzfi2NnnJSnls/UIYkMgrKruh0NLSiTjlfZQmTCgd3Yb4Ovg4TpUFwYERcRF5PUJiIgeN6VDkkZVwlGOz1J7dGThnmCQsKK7ersULcT4rjacfRdHr3HdowPA0aAUDud30tc=
  - secure: llSQmehRFk+pUS3pB9Qt07OcwCHNaF5GpOBrb922ddiFdd17ka5hPzc69Jfzo/sbQboJP4/Xk56ZRYSacUA7DzURM6m/+CRH3LQJLNSzZbmywRPh9503hupMToWRIWuy4VppCohxHIGHYnkKNUAXh33a1rdieyTkPOhFohoIj8M7xdtWtbyWqZP6VQulvthx6PP+IS2qw37KRdWw75JXDN0EayYej8Gt9fpoT0ypbfnROs7U/Ey6qnC3ICCXiQxP8Mryc50Xh1auuKBczqMHNOHRpFL/A7G1SarFVamTm3OozT2Q8aBpYYZBJMTl/hEMIK8OcfpMDNRXYszMcwcX2s8rl6Uhh1oBM3wrwDrylc4Z6WZWSdyfLc01e8rV4k96t6m9x0WGzLg9rYCKqch7AMJ6882ynp9gjMvWhhXLnkrYmbM21pDe7D+iWqIHOwduDKo7dyCg/RXfsOlvVpTbAYwJnY/lNTCc0q4LTtStZuvbK9AuGy2ZuNFp2bBFYIGPErOWV97dCF+Gsks/uvtdYmV1iwmHe13p5j8fRY844vWFWmy4hPZ7/Hjw+1w/HjX9lEwl2mqRCyJE/lK8SOfDoh6FDEPDWSMHEeMZf8nvDydYYApjWQoFdgIiDPdxUt3RZjelUzRCEqNQ412jko9x7NF4opiE8NT2dBhFQBnvzL0=
  - secure: nsCacmYOP/wASygt7FJUkIabyBCbGAXpB1FTeJ20LKxqgKg1dSYxBg97CyFKPG1Klj6RWRuzbLSfTJWPjci4ntxNyK6alMSvlj2ZsgKx6fJAeTKPnctHtl9NAgpIoh0+vjCLAHT6BZ/aAUjqByspmg7nWaiAZq17z8O44+PRDNJb64XyPvIdgjMNy2zfX8JgUjJlozJqpuSM1dgEoL9slc/20cvzxRWlYBGUTcZGeGiJroRPlmDCTCu4DPJrfMwjgVl+/Ah52i5unDNpoM5xJnkqHlVQCVL7Iw1//nV+lAOQWSDyusOCIDu0ac6FtkxCV5FASAy+OCtqFISLNRVkHv8dVKEH/XIsmcmUHXt1xmik5lqL/s6onE3C1JGLiZsoxZT4o5MtWMdESP+MrnRaioB1qsVEkqfOERNAoAJ+CXWkzMII0M3bMRrUNQOa6VfkreUrcqq9NnFie/BLXfvRapaYhXxJ+B/zWNd+MZe2ZNyjNCnDNYYKBUU9c4HKfXxPledBmb1eUfajL4hd/0d04PzqXNxmLc66Yfn7jpIcSRIurzO+KxSon4+ZQw9opQrYylIbOgfPt9heUAUOmoKjHOY7uebLb1G4sDsIQZYZ1m3q1dkWw1Prnuj3mC+ineMMdQHo4Vg3DAszCDWm7pGuXnxeT+kvyanr5xVovN76cMA=
services:
- docker
before_install:
- docker pull openjdk:8-jre-alpine
script:
- |
  if [[ -n "$TRAVIS_TAG" ]]; then
    echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
    ./gradlew dockerPush
  else
    ./gradlew check
  fi
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
