language: java
jdk:
- oraclejdk8
services:
- docker
before_install:
- docker pull openjdk:8-jre-alpine
script:
- |
  echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    ./gradlew dockerPushLatest
  elif [ "$TRAVIS_BRANCH" == "sitewhere-*" ]; then
    ./gradlew dockerPushEdge
  else
    ./gradlew check
  fi
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
