language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: llSQmehRFk+pUS3pB9Qt07OcwCHNaF5GpOBrb922ddiFdd17ka5hPzc69Jfzo/sbQboJP4/Xk56ZRYSacUA7DzURM6m/+CRH3LQJLNSzZbmywRPh9503hupMToWRIWuy4VppCohxHIGHYnkKNUAXh33a1rdieyTkPOhFohoIj8M7xdtWtbyWqZP6VQulvthx6PP+IS2qw37KRdWw75JXDN0EayYej8Gt9fpoT0ypbfnROs7U/Ey6qnC3ICCXiQxP8Mryc50Xh1auuKBczqMHNOHRpFL/A7G1SarFVamTm3OozT2Q8aBpYYZBJMTl/hEMIK8OcfpMDNRXYszMcwcX2s8rl6Uhh1oBM3wrwDrylc4Z6WZWSdyfLc01e8rV4k96t6m9x0WGzLg9rYCKqch7AMJ6882ynp9gjMvWhhXLnkrYmbM21pDe7D+iWqIHOwduDKo7dyCg/RXfsOlvVpTbAYwJnY/lNTCc0q4LTtStZuvbK9AuGy2ZuNFp2bBFYIGPErOWV97dCF+Gsks/uvtdYmV1iwmHe13p5j8fRY844vWFWmy4hPZ7/Hjw+1w/HjX9lEwl2mqRCyJE/lK8SOfDoh6FDEPDWSMHEeMZf8nvDydYYApjWQoFdgIiDPdxUt3RZjelUzRCEqNQ412jko9x7NF4opiE8NT2dBhFQBnvzL0=
services:
- docker
before_install:
- docker pull openjdk:8-jre-alpine
script:
- |
  if [[ -n "$TRAVIS_TAG" ]]; then
    echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
    ./gradlew dockerPush
  else
    ./gradlew check
  fi
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
