language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: eAjOEf0/ceqNKL3E9Z1hDX1l8LtBiHFhde3nwxMfcyL9Ktw1xbNtC5KWOA7TDbvPS2z5K+VkV0adXfbP1wc2zXpC6OQoccv8c2FePMF5BdfycqeaAFo423OE/ECVX2dZMEWMwP75+ICmL/ex5bjqCe5TbHduQcq/NpNxVbqYO1bl/q/EIz05mug4T6G96CtAkrV1ywqvfMwrSqHDhOJJtYKjArGpIAdfYSB6tUk58uyvz++GGWTg01D+goR7ZXUgL0ABZuAtt3uHlqqTiG2qZ3ERex3PKuHdKBYD9IW0L+xd0NrRvGG94mUHAD6R/63M6rKN9qKGdVt/4VwvZQKK7Ku7B8QNuHmGQgEeAeLR0/AwmG7INWL+uqSwb1tdpN0IQjMRuuorxDvnCjYOLZlrB42yd6P7tOgf5fisTf2zp8vI4i9bsT/OQ8T+mWuEaxrkSS4Cb0cnKnx52t83RoRy+KoSV7a9UvvAOXa07I1FlJ6tKQVEPQ4+qCQeWCOS9+Uvz44O4PSpZPJNvqU7Zv2ybaoEWRcb2bHZpbDMkUgsWHjyJ3W9uUSuzUuXeGsh4RVGuGgFPGWwvXBo5FCZGcuBbW1jScPWYjTg076VpB/YO3UrntYW2h7CcW6hz6X+kJV9G1YG5GBuLF3/pKgf8S1cMV6mIeGfliH4VqYgK+d0IYE=
  - secure: VGuLO1lJaoRXLW6m/fUNTAeBbXyXKY5Z2C6fo0T17Y6C4NFkFV+Q7IW5+vmVGu8jg+qaIgXjkw/uezlquOZmps2s5thHtIgP4vVhaAe6JffS6GsHPT6sOgzhnqQJOqwIogDoSWlDCGFouaJNfbsWIteAWMcuuCLQy4pf7wbQpcVsKJrS6Fzb3iIOw1O7BBcTqv7OyVlisB7nahSw7FRuZpFuEL9qjg4sVPMqr4MZ8OYy/hJOrW4G+LAUlccvPbRjGo27lwbAyrfbOBwzet1W+l5oOVkIxAAqS4xDBvEXIl8kGAssQGkoBukqNFFoXoeVCAOYj/hkrWmldTJ2j+ceeg/YIsXxr64S8ntRpE9yVaQ5g3JPpnx9/l1HpHgsHM7FLVA5r3ILxARTEUTOnReEAuKg4HbknsQ0aSEJL3sPxVVhZosHMr7jufrEMzxbuPauRGP4ep2WD2Vw2DDKvGtIr523e25t3styBvjDySitvuqLebr3wu7BwSL/5KzqJhzeDY5n69GkAoUtJFjoQjsYqLJhBTUimHhWPUBLS7h/W2KpNfKz1KQJKJcF5zOqc2irr/3oNh5Rc/NSWl0E9UwE0GcrHg4lNQMM0ooKTifo67ibkWTQr+ga1e4DXwHPUgCxg8nBx/vC3xOCe8NI5P/1zmlbUB/4U44QD4Hop82H3Pc=
  - secure: kVtwsQOBLeAt/21DF8LW2Ao0rtqtlEuTwvn3ioPtNWivtMcE3QTNkuByi2hY8UFNCIbckfdavr8cjAmXj9g1yh1HtacpOKN9QI+wph/BWVu64cluepH4kAW8e7wE2yz5G0C1fCVOTDAEu+kdJIb3qtwK6JokcJFtiN30CJMuBkplDg2fp3YpQHQlAeFkWAKpepbZ0WJM4/ahqVIxRRMcHYqfYLaFNoBIluwiEZ6NB0Dt0kvZAUv2q6163nBIRyL0TdeSQ4yjgDbhh+tr1gkwWYMhArhNHsw6pmwNfxVsu6tTEV91HSGOx7HWG7zdCy8ONPbnmT5ye/2MN6zOeB/NMOGWFyFQeGUrjN22fis/HYbWW7eIxT+z9vcElfe04xzNDa+6AJQA9x8009rc/XGdw9JiZ4zfxstxTBxwdg5eVoNvYjxaTz0HepjeM1CN2HLowu0llYh7mlGyzgDf5qREJmF4MW8zWZwcUc+ALzZEJYbbO8MyfRavA5X5dOoxDB7t8OhrOmVuT3ftejNSwobuXOEojxqa3i40Wf9C8DFfYZMWIObcJX9p76ZgH+1OPNflRb1v/2+w0jlZ+Z/CQLoOU4e/uzFV67HDOThBb3XfiE9dmEEdO148wT4WuWc5RTQpDNN5LbJ/nYRo5ysR7dQWsoxhZeRTB+/z3eLz+XeHUJg=
services:
  - docker
script:
- |
  if [[ -n "$TRAVIS_TAG" ]]; then
    ./gradlew dockerPush
  else
    ./gradlew check
  fi
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
