language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: gvBW0DEK4zgOznKNbApmeL2O3f4SWtnklXF5Yl7SjUV3ElVzdUnz6moFi6swHCRCpphFHCjkiVAWYPnmGCRHF9gRhUNzIJeoZ3ZBK+zTqaXu4WnKOWPMeXI6+is90nTgBwRCyyUh8HHLjNojFFPd8FbZNgVviQHFi/QU9nI4Y7utlDsrNKuOarzet0UGxSGnCVUqPI92UjokPBnqQrW/ShyTxT2OzNQ7kH8R/OdW2ipnTPaESurMVF7CGqnvnwOEk/WVK4SEkSBMl/zPqJC+Gs99mYoHUaa3Zvy7F+1m7S17ubQXlvRvluw8SUG+tK9TvpNTjNOAqJhEA49V9CZzYz2mqUBryLxHTsxWfwKliiU6gcT7vol6ZkHednQo/E66hON79sFJGihAGB6oGk0hFoxOYDEOFzVoE0yXMSMkHnZ+SSrzKNmSs0DjXphxIhVv0zl9gaZEp4mIxvQvfFMD6L5V/QgPeJvBzRHj1DYNzqkCd+9U8bIOTXgl35HefmH87hyKLaV+l4Nr/CdeIgrskltJppb15Qzp8k0sx+L+hTVU7SR4JKRkDEcTKQKNEdYBNnK3WKXhEKiFLS9nchmVRvx/NhIFvtM8IjgcvnXkqNxQdtNY7asIe3cM7daStnVObuk5VCDj8V0AG4zR7FnhHKTsT98DAqB8kuAHVV2BCUU=
  - secure: NOCamcTJaH5PgVWKVhycv1Dy9IV29ZcUzGVgPIjnqbIyOOi9ZQIs+d+LsbQJWzsHeUXGndwQO35p9AUTHSkFCwe/Dc43SznqOTpc7++QUwoT8yUZTaLYjQcbhFX+irSENVDrwzQKStSlG2N3mL+fmuK3pTh2rB4frOcXojFFL0jTVH4BN52btVvhAlqCl02+Nntv5lB19amMkcGyYq1CDR/k3+RrTCv0XmDbX/uHFUtDAPn/YbWLNkuQJeJIt9az05vfNQqj5udlonCdGtOSo7DJAeXpZEJkeGTJZCUxXEzYrzlOgZKOehKZUERBtef/+k7pqrRPD7/BLthcQh+7lRk5UQ3+ZC+HUn3uIJCjayl82RR/nmyeIlU/626Kv5JNkMnzmtsixmLhXtcwTMUaUT7Z57EYkPSCrH9r3dFGM3jwSQYQiLZBpwXWoXyheqa6Na2gvAcPekVhrgpDg+mX1F0EFa986u0iNpzDwDMS0x7V5AwOW7CC0sW2Ll4GoNPWt/JAqH0pgrPcjx42zccfIehxtV9XgnIVrYJuR8XdpExdynEQhHQfSeMxssUv8y8oKnfGZZLaOt3+Xz3b1tQa5/jtT6hjuS1nq1XN9GAmpMeIW7vTo1SCfvRG9mJ6GDJG5pKhB1OAt812YHlUqXt/uaV6pDHS8L4wktaWrCXjOvw=
  - secure: R9gFRS5HQrfzwkqCOef/9lFN5PsqOS1wE9WC4M02wvxISRz75AHXN3DRCKpSodMsP8gfpoEAk02CVr7d8ZTyjJ1LhFPlgm1COAZu0HZvkWPk11L8PGo1nMY2Nui/htTnESohDje1hFvD5vhO2OphpsgRbMmsmEzpAbBMR7cx6A1TBUqhBnsG4+5N5ziHW+LfkLkG53MPjdGRU5cBJacgz97ATD29efjW3+qITk6YormOeHQTUJzzypPQRc4E+ljKetSMKeGqfleuntaqOjxqKIOvo7SOg03CBvTJNmP1EoESZHXkbCKWY0dYGWqmdyHza0iswbKH7Xzy9W/86E3YAimVpCBzISvwsiCMd2ay5Z4ymQ9FF8aMFLYo8Z8mIPEghmOKJ6snAN/d0FwNA9l7SybQ41WdoMa6RUzHvfGHZoPk0QPQwEk5B3MkPCF2eyHMb7/9+4tBIO/E0SaunxASaZ5A6L4EtkOVlQNd3rztvlbKemSggO/HuPbVP0UP2U1QPq7nSWYuSsyt0O47BMB2zO75XfM593b4nBH2MoR31C4wDm6/3kIY9ggHoaSDNAC11PpoFg0uidtLjUYY5Dz5/Xa27i2iq27/uvwL3eJ9mwJZ6pJMlOOe8Rx6kTmMIiTZ3+Qy3T2fV5WY2A36BJ93UqjMyfXhNaFonpVnbUX5g1Q=
services:
- docker
before_install:
- docker pull openjdk:8-jre-alpine
script:
- |
  if [[ -n "$TRAVIS_TAG" ]]; then
    echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
    ./gradlew dockerPush
  else
    ./gradlew check
  fi
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
